mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&serverTimezone=UTC
        username: test

    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 5000ms